ALE/SpaceInvaders-v5:
  env_wrapper:
    stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  policy: "CnnPolicy"
  n_timesteps: 10000
  buffer_size: 10000
  learning_rate: 0.001
  batch_size: 32
  learning_starts: 100
  target_update_interval: 100
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_final_eps: 0.01
  optimize_memory_usage: False